### PR TITLE
feat: cache input files

### PR DESCRIPTION
**Pull request by alebianco**
be a good AOC citizen and download the input file only once

https://www.reddit.com/r/adventofcode/comments/a1qovy/please_dont_spam_requests_to_aoc/

### CODE REVIEW

**Comment by C-Jansek** [comment]
Would be really nice if this PR can be accepted before the start of this years AoC!

**Comment by mariofdezzz** [comment]
Hi Alessandro 👋🏼

First of all, I would like to thank you for you contribution.

Right now, fetch requests only runs once, on command execution. Request is saved on program cache, and used during continuous executions with nodemon. Until command is stopped, request will keep on memory.
On a common workflow will execute command once, and test code multiple times using automatic reexecution, avoiding continous requests.

As the author pointed out: _Please throttle your requests to at least once every few minutes_. This should be accomplished by far using a common workflow. Your ip won't be banned.

I don't see an explicit need of using disk cache, and I would like to avoid it.

I beg your pardon for answering so late and thanks again for your contribution.

**Comment by alebianco** [comment]
tnx @mariofdezzz for the feedback

I don't fully agree with that, since it holds true only until you stop and then restart the cli. which (in my case at least) happens "often"

If you take a look at any other cli/helper for aoc, they all cache to disk and NEVER repeat the request.

I'll keep using my fork for now, but I'll keep an eye on your development to see where the stable release lands 👍

**Comment by mariofdezzz** [comment]
I'll consider it 👍🏼

**Pull request closed without merging**
